Repository crane-cloud/frontend, pull requests merged in 2020-04, with the labels that each got.

#97 Fix no resource div for Cluster Elements
  src/components/DeploymentsPage/index.js
  src/components/JobsListPage/index.js
  src/components/NamespacesList/index.js
  src/components/NodesList/index.jsx
  src/components/PodsList/index.jsx
  src/components/PvcsList/index.js
  src/components/PvsListPage/index.js
  src/components/ServicesList/index.js
  src/components/SideNav/SideNav.css
  src/components/SideNav/index.jsx
  src/components/StorageClassList/index.js
  src/index.css
  src/redux/actions/actionTypes.js
  src/redux/reducers/NamespacesListReducer.js
  src/redux/reducers/PvsReducer.js
  src/redux/reducers/appsListReducer.js
  src/redux/reducers/clustersReducer.js
  src/redux/reducers/getDeployments.js
  src/redux/reducers/index.js
  src/redux/reducers/jobsReducer.js
  src/redux/reducers/nodesReducer.js
  src/redux/reducers/podsReducer.js
  src/redux/reducers/pvcsReducer.js
  src/redux/reducers/servicesReducer.js
  src/redux/reducers/storageClassReducer.js
  src/router.js
Labels: ready-for-review

#100 Work on login fix and reposition buttons on add project form and clear state on login
  src/components/ClustersList/index.jsx
  src/components/Header/index.js
  src/components/LoginPage/index.js
  src/components/UserProjectsPage/index.jsx
  src/redux/actions/ClustersActions.js
Labels: ready for review

#101 Fix user Apps and Projects pages cashe issue
  src/components/AppsList/index.jsx
  src/components/AppsPage/index.jsx
  src/components/UserProjectsPage/index.jsx
  src/redux/reducers/appsListReducer.js
  src/redux/reducers/userProjectsReducer.js
Labels: ready-for-review

#105 Bug fix get projects routing error
  src/components/UserProjectsPage/index.jsx
  src/redux/actions/addProject.js
  src/redux/actions/projectsListActions.js
Labels: ready-for-review

#102 Change Add App modal layout
  src/components/AppsPage/AppsPage.css
  src/components/AppsPage/index.jsx
  src/components/BlackInputText/index.jsx
  src/components/Modal/Modal.css
Labels: ready for review

#104 Redo create cluster without library
  .eslintrc.json
  src/components/AddClusterForm/index.jsx
  src/components/AppsPage/AppsPage.css
  src/components/ClusterPage/index.jsx
  src/redux/actions/actionTypes.js
  src/redux/actions/addCluster.js
  src/redux/reducers/addClusterReducer.js
Labels: ready for review

#108 Production docker image
  docker/dev/Dockerfile
  docker/prod/Dockerfile
Labels: ready for review

#103 Feature Add project description
  src/components/TextArea/TextArea.css
  src/components/TextArea/index.js
  src/components/UserProjectsPage/index.jsx
  src/redux/actions/projectsListActions.js
Labels: ready for review

#106 Fix adding tokens by individual pages issue
  src/components/AdminLoginPage/index.js
  src/components/AppsPage/index.jsx
  src/components/Header/index.js
  src/components/LoginPage/index.js
  src/redux/actions/projectsListActions.js
Labels: bug fix, ready for review

#109 customize error for conflicting app names
  src/components/AppsPage/index.jsx
  src/redux/actions/createApp.js
  src/redux/reducers/createApp.js
Labels: ready-for-review

#112 Bug Fix remove redundant code
  src/components/AddProject/AddProject.css
  src/components/AddProject/index.js
  src/components/TableList/TableList.css
  src/components/TableList/index.js
  src/helpers/allClusters.js
Labels: ready for review

#107 Feat add delete to apps
  src/assets/images/3dots.svg
  src/components/AppsCard/AppsCard.css
  src/components/AppsCard/index.jsx
  src/components/AppsList/index.jsx
  src/redux/actions/actionTypes.js
  src/redux/actions/deleteAppActions.js
  src/redux/reducers/DeleteAppReducer.js
  src/redux/reducers/index.js
Labels: ready-for-review

#114 Cleanup - remove unused components
  package.json
  src/components/AddClusterForm/AddClusterForm.css
  src/components/AddClusterForm/index.jsx
  src/components/CreateAppForm/index.js
  yarn.lock
Labels: ready for review

#111 Ft validate create project form
  src/components/UserProjectsPage/UserProjectsPage.css
  src/components/UserProjectsPage/index.jsx
Labels: ready-for-review

#121 Fix Cluster Card Image Background and login overflow styling
  src/components/LoginPage/LoginPage.css
  src/components/ProjectsList/ProjectsList.css
  src/components/RegisterPage/RegisterPage.css
  src/components/UserProjectsPage/UserProjectsPage.css
Labels: ready-for-review

#120 Fix no resources message on Admin Dash
  src/components/ClusterResources/ClusterResource.css
  src/components/ClusterResources/index.js
  src/components/ClusterResourcesPage/ClusterResourcesPage.css
  src/components/ClusterResourcesPage/index.jsx
  src/index.css
  src/redux/reducers/ClusterResourcesReducer.js
Labels: ready for review

#123 Create simple user avatar
  src/assets/images/profile.svg
  src/components/Header/Header.css
  src/components/Header/index.js
Labels: ready for review

#119 Change admin projects view, from Card view to List View
  src/components/AdminProjectsPage/AdminProjectsPage.css
  src/components/AdminProjectsPage/index.js
  src/redux/actions/UserDetailActions.js
  src/redux/actions/actionTypes.js
  src/redux/actions/usersActions.js
  src/redux/reducers/AdminProjectsReducer.js
  src/redux/reducers/index.js
  src/redux/reducers/userDetailReducer.js
  src/redux/reducers/usersListReducer.js
Labels: ready-for-review

#113 Bg fix project dropdown feedback
  src/components/UserProjectsPage/UserProjectsPage.css
  src/components/UserProjectsPage/index.jsx
Labels: ready-for-review

#124 Feature Admin view of user accounts
  src/components/SideNav/index.jsx
  src/components/UserAccounts/UserAccounts.css
  src/components/UserAccounts/index.js
  src/redux/reducers/usersListReducer.js
  src/router.js
Labels: ready-for-review

#126 Style feedback message
  src/index.css
Labels: ready for review

#125 Change backend Api url to from cluster to staging
  .gitignore
  src/config.js
Labels: ready-for-review

#128 sanitize app name
  src/components/AppsPage/index.jsx
Labels: ready-for-review

#127 Create a reusable component for feedback
  src/components/AppsCard/AppsCard.css
  src/components/AppsCard/index.jsx
  src/components/AppsPage/AppsPage.css
  src/components/AppsPage/index.jsx
  src/components/ClusterPage/index.jsx
  src/components/Feedback/Feedback.css
  src/components/Feedback/index.js
  src/components/UserProjectsPage/UserProjectsPage.css
  src/components/UserProjectsPage/index.jsx
  src/index.css
Labels: ready for review

#129 Fix page stylings on develop
  src/components/ClusterPage/ClusterPage.css
  src/components/UserProjectsPage/UserProjectsPage.css
  src/index.css
Labels: ready-for-review

#130 Remove bindActionCreators
  src/components/AdminProjectsPage/index.js
  src/components/AppsCard/index.jsx
  src/components/AppsList/index.jsx
  src/components/ClusterResourcesPage/index.jsx
  src/components/ClustersList/index.jsx
  src/components/JobsListPage/index.js
  src/components/NamespacesList/index.js
  src/components/NodesList/index.jsx
  src/components/PodsList/index.jsx
  src/components/ProjectsList/index.jsx
  src/components/PvcsList/index.js
  src/components/PvsListPage/index.js
  src/components/ServicesList/index.js
  src/components/StorageClassList/index.js
  src/components/UserAccounts/index.js
  src/components/UserProjectsPage/index.jsx
Labels: ready-for-review

#131 From PascalCase to camelCase
  src/components/AdminProjectsPage/index.js
  src/components/AppsCard/index.jsx
  src/components/AppsList/index.jsx
  src/components/ClusterPage/index.jsx
  src/components/ClusterResourcesPage/index.jsx
  src/components/ClustersList/index.jsx
  src/components/JobsListPage/index.js
  src/components/NamespacesList/index.js
  src/components/NodesList/index.jsx
  src/components/PodsList/index.jsx
  src/components/ProjectsList/index.jsx
  src/components/ProjectsList/indexs.js
  src/components/PvcsList/index.js
  src/components/PvsListPage/index.js
  src/components/ServicesList/index.js
  src/components/StorageClassList/index.js
  src/components/UserAccounts/index.js
  src/components/UserProjectsPage/index.jsx
  src/config.js
  src/redux/actions/addCluster.js
  src/redux/actions/addProject.js
  src/redux/actions/adminProjects.js
  src/redux/actions/appsList.js
  src/redux/actions/clusterResources.js
  src/redux/actions/clusters.js
  src/redux/actions/deleteApp.js
  src/redux/actions/jobs.js
  src/redux/actions/namespaces.js
  src/redux/actions/nodeCluster.js
  src/redux/actions/pods.js
  src/redux/actions/projectsList.js
  src/redux/actions/pvcs.js
  src/redux/actions/pvs.js
  src/redux/actions/services.js
  src/redux/actions/storageClasses.js
  src/redux/actions/userDetails.js
  src/redux/actions/users.js
  src/redux/reducers/addCluster.js
  src/redux/reducers/addProject.js
  src/redux/reducers/adminProjects.js
  src/redux/reducers/appsList.js
  src/redux/reducers/clusterResources.js
  src/redux/reducers/clusters.js
  src/redux/reducers/deleteApp.js
  src/redux/reducers/index.js
  src/redux/reducers/jobs.js
  src/redux/reducers/namespacesList.js
  src/redux/reducers/nodes.js
  src/redux/reducers/pods.js
  src/redux/reducers/projectsList.js
  src/redux/reducers/pvcs.js
  src/redux/reducers/pvs.js
  src/redux/reducers/services.js
  src/redux/reducers/storageClass.js
  src/redux/reducers/userDetails.js
  src/redux/reducers/userProjects.js
  src/redux/reducers/usersList.js
Labels: ready for review

#133 Feat reload projects page on project creation
  src/components/UserProjectsPage/index.jsx
  src/redux/actions/actionTypes.js
  src/redux/actions/addProject.js
  src/redux/reducers/addProject.js
Labels: ready-for-review

#134 Fix project page issue for 1st time logged in user
  src/components/VerificationSentPage/index.js
Labels: ready for review

#135 Re-render apps on delete
  src/components/AppsCard/index.jsx
  src/components/AppsList/index.jsx
  src/redux/actions/actionTypes.js
  src/redux/actions/deleteApp.js
  src/redux/reducers/deleteApp.js
Labels: ready for review

#136 Optimize input elements
  src/components/BlackInputText/index.jsx
  src/components/InputPassword/index.js
  src/components/InputText/index.js
  src/components/TextArea/index.js
Labels: ready for review

#137 re-align logo in header
  src/components/Header/Header.css
Labels: ready-for-review

#116 Feature delete user project
  src/components/ProjectCard/ProjectCard.css
  src/components/ProjectCard/index.js
  src/components/UserProjectsPage/index.jsx
  src/config.js
  src/redux/actions/actionTypes.js
  src/redux/actions/deleteProject.js
  src/redux/actions/projectDetail.js
  src/redux/actions/updateProject.js
  src/redux/reducers/deleteProject.js
  src/redux/reducers/index.js
  src/redux/reducers/projectDetail.js
  src/redux/reducers/updateProject.js
Labels: ready-for-review

#139 Fix issue with projects alignment
  src/components/ProjectCard/index.js
Labels: ready-for-review

#141 Custom select component
  src/assets/images/down-arrow-black.svg
  src/components/Select/Select.css
  src/components/Select/index.js
  src/components/UserProjectsPage/index.jsx
Labels: ready for review

#138 Fix create button
  src/components/ButtonComponent/ButtonComponent.css
Labels: ready-for-review

#140 restore config file
  src/config.js
Labels: ready-for-review

#143 Adds a tool-tip component
  src/assets/images/info-icon.svg
  src/components/AppsPage/AppsPage.css
  src/components/AppsPage/index.jsx
  src/components/Tooltip/Tooltip.css
  src/components/Tooltip/index.js
Labels: ready for review
