Repository crane-cloud/frontend, pull requests merged in 2020-03, with the labels that each got.

#58 Ft create new password
  src/components/CreateNewPassword/CreateNewPassword.css
  src/components/CreateNewPassword/index.jsx
  src/router.js
Labels: ready-for-review

#63 Feat Show cluster pods
  src/components/ClusterResourcesPage/index.jsx
  src/components/PodsList/PodsList.css
  src/components/PodsList/index.jsx
  src/components/SpinnerComponent/index.js
  src/components/Status/Status.css
  src/components/Status/index.js
  src/helpers/ageUtility.js
  src/redux/actions/actionTypes.js
  src/redux/actions/podsActions.js
  src/redux/reducers/index.js
  src/redux/reducers/podsReducer.js
  src/router.js
Labels: good first issue, ready for review

#60 Feature Namespaces list page
  src/components/CreateNewPassword/index.jsx
  src/components/NamespacesList/NamespacesList.css
  src/components/NamespacesList/index.js
  src/components/SideNav/SideNav.css
  src/components/Status/Status.css
  src/components/TableList/index.js
  src/redux/actions/NamespacesActions.js
  src/redux/actions/actionTypes.js
  src/redux/reducers/NamespacesListReducer.js
  src/redux/reducers/index.js
  src/router.js
Labels: ready for review

#61 Feature Show Persistent Volume Claims list for a Cluster
  src/components/PvcsList/PvcsList.css
  src/components/PvcsList/index.js
  src/redux/actions/PvcsActions.js
  src/redux/actions/actionTypes.js
  src/redux/reducers/index.js
  src/redux/reducers/pvcsReducer.js
  src/router.js
Labels: ready for review

#64 Ft show nodes
  src/components/ClusterResourcesPage/index.jsx
  src/components/NodesList/NodesList.css
  src/components/NodesList/index.jsx
  src/redux/actions/actionTypes.js
  src/redux/actions/nodeClusterActions.js
  src/redux/reducers/index.js
  src/redux/reducers/nodesReducer.js
  src/router.js
Labels: ready-for-review

#67 feat(add routes to SideNav) updates routes for sideNav
  src/components/SideNav/SideNav.css
  src/components/SideNav/index.jsx
Labels: ready-for-review

#68 Ft admin jobs page
  src/components/JobsListPage/JobsListPage.css
  src/components/JobsListPage/index.js
  src/components/NavBar/index.jsx
  src/redux/actions/JobsActions.js
  src/redux/actions/actionTypes.js
  src/redux/reducers/index.js
  src/redux/reducers/jobsReducer.js
  src/router.js
Labels: ready for review

#66 Feature Volumes list as Admin
  src/components/PvsListPage/PvsListPage.css
  src/components/PvsListPage/index.js
  src/components/Status/Status.css
  src/redux/actions/PvsActions.js
  src/redux/actions/actionTypes.js
  src/redux/reducers/PvsReducer.js
  src/redux/reducers/index.js
  src/router.js
Labels: ready for review

#69 Show Admin storage classes
  src/components/PodsList/index.jsx
  src/components/StorageClassList/StorageClassList.css
  src/components/StorageClassList/index.js
  src/redux/actions/StorageClassesActions.js
  src/redux/actions/actionTypes.js
  src/redux/reducers/index.js
  src/redux/reducers/storageClassReducer.js
  src/router.js
Labels: ready-for-review

#71 fix(Show ServicePorts)Adds Ports
  src/components/ServicesList/index.js
Labels: help wanted, question

#72 Bug fix pods
  public/index.html
  src/components/PodsList/index.jsx
Labels: ready for review

#70 Fix (big spinner) adds Spinner on components
  src/components/DeploymentsPage/index.js
  src/components/JobsListPage/index.js
  src/components/NamespacesList/index.js
  src/components/NodesList/NodesList.css
  src/components/NodesList/index.jsx
  src/components/PodsList/index.jsx
  src/components/PvcsList/index.js
  src/components/PvsListPage/index.js
  src/components/ServicesList/index.js
  src/components/SideNav/index.jsx
  src/components/StorageClassList/index.js
  src/redux/reducers/index.js
Labels: ready-for-review

#76 Feat View available projects as admin
  src/assets/images/plant.svg
  src/components/AdminProjectsPage/AdminProjectsPage.css
  src/components/AdminProjectsPage/index.js
  src/components/SideNav/index.jsx
  src/redux/actions/AdminProjectsActions.js
  src/redux/actions/actionTypes.js
  src/redux/reducers/AdminProjectsReducer.js
  src/redux/reducers/index.js
  src/router.js
Labels: ready for review

#75 Bug Fix Add Cluster Description to card and Big Spinner
  src/components/ClustersList/index.jsx
Labels: ready-for-review

#80 Fix progress bar
  src/components/ProgressBar/index.js
Labels: ready for review

#79 Ft login validation
  .eslintrc.json
  src/components/AdminLoginPage/index.js
  src/components/LoginPage/LoginPage.css
  src/components/LoginPage/index.js
Labels: ready for review

#83 Create Modal component
  src/assets/images/close.svg
  src/components/Modal/Modal.css
  src/components/Modal/index.js
Labels: ready for review

#84 Ft register page validation
  src/components/Checkbox/index.js
  src/components/RegisterPage/RegisterPage.css
  src/components/RegisterPage/index.js
Labels: ready for review

#85 Fix login redirect
  src/components/LoginPage/index.js
Labels: ready for review

#86 Show user apps list
  src/assets/images/backButton.svg
  src/components/AdminProjectsPage/index.js
  src/components/AppsCard/AppsCard.css
  src/components/AppsCard/index.jsx
  src/components/AppsList/AppsList.css
  src/components/AppsList/index.jsx
  src/components/AppsPage/AppsPage.css
  src/components/AppsPage/index.jsx
  src/components/ClusterCard/App/App.css
  src/components/ClusterCard/App/index.js
  src/components/LoginPage/index.js
  src/components/Status/Status.css
  src/components/UserProjectsPage/index.js
  src/redux/actions/actionTypes.js
  src/redux/actions/appsListActions.js
  src/redux/reducers/appsListReducer.js
  src/redux/reducers/index.js
  src/router.js
Labels: ready-for-review

#88 Fix Header Dropdown Styling
  src/components/Header/Header.css
  src/components/Header/index.js
Labels: ready-for-review

#90 Bug fix for apps not loading
  src/components/AppsList/index.jsx
  src/components/AppsPage/index.jsx
  src/redux/actions/appsListActions.js
Labels: ready-for-review

#91 Fix add status to deployments
  src/components/DeploymentsPage/index.js
Labels: ready-for-review

#94 Fix user some journey issues
  src/components/AdminProjectsPage/AdminProjectsPage.css
  src/components/AppsList/AppsList.css
  src/components/AppsList/index.jsx
  src/components/ButtonComponent/ButtonComponent.css
  src/components/ClusterPage/ClusterPage.css
  src/components/Footer/ClustersList/ClustersList.css
  src/components/Footer/ClustersList/index.js
  src/components/Header/Header.css
  src/components/Header/index.js
  src/components/InformationBar/InformationBar.css
  src/components/InformationBar/index.jsx
  src/components/InputPassword/InputPassword.css
  src/components/InputPassword/index.js
  src/components/InputText/InputText.css
  src/components/InputText/index.js
  src/components/LandingFooter/LandingFooter.css
  src/components/LandingPage/index.js
  src/components/PrimaryButton/PrimaryButton.css
  src/components/UserProjectsPage/UserProjectsPage.css
  src/components/UserProjectsPage/index.js
  src/index.css
Labels: ready-for-review

#96 Fix admin journey Focus is on the DashBoard
  src/components/AdminDashboard/AdminDashboard.css
  src/components/AdminDashboard/index.js
  src/components/AdminProjectsPage/index.js
  src/components/ClusterCard/index.js
  src/components/ClusterResourcesPage/ClusterResourcesPage.css
  src/components/ClusterResourcesPage/index.jsx
  src/components/DeploymentsPage/index.js
  src/components/JobsListPage/JobsListPage.css
  src/components/JobsListPage/index.js
  src/components/NamespacesList/NamespacesList.css
  src/components/NamespacesList/index.js
  src/components/NodesList/NodesList.css
  src/components/NodesList/index.jsx
  src/components/PodsList/PodsList.css
  src/components/PodsList/index.jsx
  src/components/PvcsList/PvcsList.css
  src/components/PvcsList/index.js
  src/components/PvsListPage/PvsListPage.css
  src/components/PvsListPage/index.js
  src/components/ServicesList/ServicesList.css
  src/components/ServicesList/index.js
  src/components/SideNav/SideNav.css
  src/components/SideNav/index.jsx
  src/components/StorageClassList/index.js
  src/components/VerificationSentPage/index.js
  src/index.css
Labels: ready for review

#95 Ft implement forgot password
  src/components/CreateNewPassword/CreateNewPassword.css
  src/components/CreateNewPassword/index.jsx
  src/components/PasswordReset/PasswordReset.css
  src/components/PasswordReset/index.js
  src/router.js
Labels: ready-for-review

#99 add return for post
  src/redux/actions/createApp.js
Labels: ready for review

#89 User able to create project
  src/components/AddProject/AddProject.css
  src/components/AddProject/index.js
  src/components/InformationBar/InformationBar.css
  src/components/InformationBarSub/InformationBarSub.css
  src/components/PrimaryButton/PrimaryButton.css
  src/components/ProjectsList/ProjectsList.css
  src/components/ProjectsList/index.jsx
  src/components/ProjectsList/indexs.js
  src/components/UserProjectsPage/UserProjectsPage.css
  src/components/UserProjectsPage/index.jsx
  src/helpers/allClusters.js
  src/redux/actions/actionTypes.js
  src/redux/actions/addProject.js
  src/redux/actions/projectsListActions.js
  src/redux/reducers/addProjectReducer.js
  src/redux/reducers/index.js
  src/redux/reducers/projectsListReducer.js
Labels: ready for review
